# https://github.com/realm/SwiftLint#configuration
# https://github.com/realm/SwiftLint/blob/master/Rules.md
disabled_rules: # Skip these rules
# disabled rules go here...

opt_in_rules:
- line_length
- vertical_parameter_alignment
- private_over_fileprivate
- identifier_name
- type_name
- force_cast
- force_try
- for_where
- unused_enumerated
- legacy_constructor
- notification_center_detachment
- multiple_closures_with_trailing_closure
- weak_delegate
- closure_end_indentation # Closure end should have the same indentation as the line that started it
- closure_spacing # Closure expressions should have a single space inside each brace.
- compiler_protocol_init # The initializers declared in compiler protocols such as ExpressibleByArrayLiteral shouldn't be called directly
- empty_count # Prefer checking isEmpty over comparing count to zero
- explicit_init # Explicitly calling .init() should be avoided
- first_where # Prefer using .first(where:) over .filter { }.first in collections
- implicit_getter # Computed read-only properties should avoid using the get keyword.
- multiline_parameters # Functions and methods parameters should be either on the same line, or one per line.
- operator_usage_whitespace # Operators should be surrounded by a single whitespace when they are being used.
- redundant_nil_coalescing # nil coalescing operator is only evaluated if the lhs is nil, coalescing operator with nil as rhs is redundant
- vertical_parameter_alignment_on_call # Function parameters should be aligned vertically if they're in multiple lines in a method call
- fatal_error_message # A fatalError call should have a message
- overridden_super_call # Some overridden methods should always call super
- force_unwrapping # Force unwrapping should be avoided
- sorted_imports
- conditional_returns_on_newline # Conditional statements should always return on the next line
- explicit_top_level_acl # Enable for pods!
- discouraged_optional_boolean #Prefer non-optional booleans over optional booleans
- sorted_first_last #Prefer using min() or max() over sorted().first or sorted().last
    
excluded: # Skip these folders
- fastlane
- Pods
- scripts
- vendor
- Carthage
- ChumBoxTests

# custom options
cyclomatic_complexity:
    warning: 12
nesting:
    type_level: 2
    statement_level: 10
trailing_whitespace:
 ignores_empty_lines: true
file_length:
 ignore_comment_only_lines: true
identifier_name:
 excluded:
  - id
  - op
  - vc
  - dy
